# Generated by Django 5.2.7 on 2025-10-10 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Assinatura'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
