# Generated by Django 5.2.7 on 2025-10-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF no formato: XXX.XXX.XXX-XX', max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
