# Generated by Django 5.2.7 on 2025-10-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_articlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Conteúdo Exclusivo?'),
        ),
    ]
