# Generated by Django 5.2.7 on 2025-10-11 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_articlepagetag_articlepage_tags'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_font', models.CharField(default='Roboto', help_text='Nome da fonte do Google Fonts (ex: Roboto, Montserrat, Playfair Display)', max_length=100, verbose_name='Fonte dos Títulos')),
                ('body_font', models.CharField(default='Merriweather', help_text='Nome da fonte do Google Fonts (ex: Merriweather, Open Sans, Lora)', max_length=100, verbose_name='Fonte do Corpo')),
                ('primary_color', models.CharField(default='#E3120B', help_text='Cor principal do site (formato hexadecimal: #E3120B)', max_length=7, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(default='#111111', help_text='Cor secundária (formato hexadecimal)', max_length=7, verbose_name='Cor Secundária')),
                ('show_video_section', models.BooleanField(default=True, help_text='Ativa/desativa a seção de vídeos curtos na home', verbose_name='Mostrar Seção de Vídeos?')),
                ('articles_per_page', models.IntegerField(default=9, help_text='Número de artigos a exibir na página inicial', verbose_name='Artigos por Página')),
            ],
            options={
                'verbose_name': 'Customização do Site',
                'verbose_name_plural': 'Customização do Site',
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='Use uma URL de imagem externa para economizar espaço. Se preenchido, será usado ao invés da imagem local.', verbose_name='URL de Imagem Externa'),
        ),
        migrations.CreateModel(
            name='VideoShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título do Vídeo')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='Descrição')),
                ('video_url', models.URLField(help_text='URL do vídeo (YouTube, Vimeo, etc.)', verbose_name='URL do Vídeo')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL externa para o thumbnail. Se preenchido, será usado ao invés da imagem local.', verbose_name='URL do Thumbnail')),
                ('duration', models.CharField(default='0:30', help_text='Formato: M:SS (ex: 1:30)', max_length=10, verbose_name='Duração')),
                ('is_featured', models.BooleanField(default=False, help_text='Vídeos destacados aparecem na seção de vídeos da home', verbose_name='Destacar na Home?')),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição (menor número aparece primeiro)', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('thumbnail_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail (Imagem de Capa)')),
            ],
            options={
                'verbose_name': 'Vídeo Curto',
                'verbose_name_plural': 'Vídeos Curtos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
