# Generated by Django 5.2.7 on 2025-10-11 22:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_sitecustomization_articlepage_external_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2), ('image_with_caption', 6), ('video', 7), ('quote', 10), ('list', 12), ('divider', 13), ('html', 14)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'help_text': 'Adicione parágrafos de texto com formatação básica', 'label': 'Parágrafo'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Adicione um título de seção', 'label': 'Título/Subtítulo'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Insira uma imagem no artigo', 'label': 'Imagem'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Legenda', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Crédito', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4), ('credit', 5)]], {'icon': 'image', 'label': 'Imagem com Legenda'}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Cole o link do vídeo do YouTube, Vimeo ou outra plataforma', 'label': 'Vídeo (YouTube, Vimeo, etc.)'}), 8: ('wagtail.blocks.TextBlock', (), {'label': 'Texto da Citação'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Autor', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 8), ('author', 9)]], {'icon': 'openquote', 'label': 'Citação'}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Item'}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Adicione uma lista de itens', 'label': 'Lista'}), 13: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Uma linha horizontal para separar seções', 'label': 'Divisor', 'template': 'content/blocks/divider.html'}), 14: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Adicione HTML personalizado (use com cuidado)', 'label': 'HTML Customizado'})}, null=True, verbose_name='Conteúdo do Artigo'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Corpo do Artigo (Legado)'),
        ),
    ]
