# Generated by Django 5.2.7 on 2025-10-11 23:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_change_publication_date_to_datetime'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('section_key', models.CharField(choices=[('em-alta', 'Em Alta'), ('geopolitica', 'Geopolítica'), ('economia', 'Economia'), ('clima', 'Clima'), ('tecnologia', 'Tecnologia'), ('escatologia', 'Escatologia')], help_text='Chave da seção que esta página representa', max_length=50, unique=True, verbose_name='Seção')),
                ('introduction', models.TextField(blank=True, help_text='Texto introdutório para esta seção', verbose_name='Introdução da Seção')),
            ],
            options={
                'verbose_name': 'Página de Seção',
                'verbose_name_plural': 'Páginas de Seção',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='section',
            field=models.CharField(choices=[('em-alta', 'Em Alta'), ('geopolitica', 'Geopolítica'), ('economia', 'Economia'), ('clima', 'Clima'), ('tecnologia', 'Tecnologia'), ('escatologia', 'Escatologia')], default='em-alta', help_text='Escolha a seção deste artigo', max_length=50, verbose_name='Seção'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2), ('image_url', 7), ('video', 8), ('quote', 11), ('list', 13), ('divider', 14), ('html', 15)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'help_text': 'Adicione parágrafos de texto com formatação básica', 'label': 'Parágrafo'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Adicione um título de seção', 'label': 'Título/Subtítulo'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Insira uma imagem do banco de dados', 'label': 'Imagem (Somente Upload)'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem (Upload)', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Ou use uma URL de imagem externa', 'label': 'URL da Imagem', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Legenda', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Crédito', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 3), ('image_url', 4), ('caption', 5), ('credit', 6)]], {}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Cole o link do vídeo do YouTube, Vimeo ou outra plataforma', 'label': 'Vídeo (YouTube, Vimeo, etc.)'}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Texto da Citação'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Autor', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 9), ('author', 10)]], {'icon': 'openquote', 'label': 'Citação'}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Item'}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Adicione uma lista de itens', 'label': 'Lista'}), 14: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Uma linha horizontal para separar seções', 'label': 'Divisor', 'template': 'content/blocks/divider.html'}), 15: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Adicione HTML personalizado (use com cuidado)', 'label': 'HTML Customizado'})}, null=True, verbose_name='Conteúdo do Artigo'),
        ),
    ]
