# Generated by Django 5.2.7 on 2025-10-12 03:17

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_sectionpage_articlepage_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='is_featured_highlight',
            field=models.BooleanField(default=False, help_text='Marque para destacar este artigo independente da data de publicação', verbose_name='Artigo de Alto Impacto?'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='title_font',
            field=models.CharField(choices=[('Roboto', 'Roboto (Padrão)'), ('Playfair Display', 'Playfair Display (Elegante)'), ('Merriweather', 'Merriweather (Clássico)'), ('Montserrat', 'Montserrat (Moderno)'), ('Lora', 'Lora (Serifa)'), ('Open Sans', 'Open Sans (Clean)'), ('PT Serif', 'PT Serif (Jornal)'), ('Georgia', 'Georgia (Tradicional)')], default='Roboto', help_text='Escolha a fonte para o título deste artigo', max_length=100, verbose_name='Fonte do Título'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2), ('image_url', 7), ('video', 8), ('quote', 11), ('list', 13), ('divider', 14), ('html', 15)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'code', 'superscript', 'subscript', 'blockquote'], 'help_text': 'Adicione parágrafos de texto com formatação completa', 'label': 'Parágrafo'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Adicione um título de seção', 'label': 'Título/Subtítulo'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Insira uma imagem do banco de dados', 'label': 'Imagem (Somente Upload)'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem (Upload)', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Ou use uma URL de imagem externa', 'label': 'URL da Imagem', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Legenda', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Crédito', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 3), ('image_url', 4), ('caption', 5), ('credit', 6)]], {}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Cole o link do vídeo do YouTube, Vimeo ou outra plataforma', 'label': 'Vídeo (YouTube, Vimeo, etc.)'}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Texto da Citação'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Autor', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 9), ('author', 10)]], {'icon': 'openquote', 'label': 'Citação'}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Item'}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Adicione uma lista de itens', 'label': 'Lista'}), 14: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Uma linha horizontal para separar seções', 'label': 'Divisor', 'template': 'content/blocks/divider.html'}), 15: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Adicione HTML personalizado (use com cuidado)', 'label': 'HTML Customizado'})}, null=True, verbose_name='Conteúdo do Artigo'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='introduction',
            field=wagtail.fields.RichTextField(help_text='Introdução do artigo (até 500 caracteres) com formatação básica', max_length=500, verbose_name='Introdução'),
        ),
    ]
