# Generated by Django 5.2.7 on 2025-10-12 23:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_articlepage_is_featured_highlight_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Texto introdutório para a página de vídeos', verbose_name='Introdução')),
            ],
            options={
                'verbose_name': 'Página de Vídeos',
                'verbose_name_plural': 'Páginas de Vídeos',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2), ('image_url', 7), ('gif', 9), ('audio', 13), ('pdf_download', 17), ('video', 18), ('quote', 21), ('list', 23), ('divider', 24), ('html', 25)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'code', 'superscript', 'subscript', 'blockquote'], 'help_text': 'Adicione parágrafos de texto com formatação completa', 'label': 'Parágrafo'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Adicione um título de seção', 'label': 'Título/Subtítulo'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Insira uma imagem do banco de dados', 'label': 'Imagem (Somente Upload)'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem (Upload)', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Ou use uma URL de imagem externa', 'label': 'URL da Imagem', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Legenda', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Crédito', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 3), ('image_url', 4), ('caption', 5), ('credit', 6)]], {}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': 'Cole a URL do GIF (ex: de um serviço como Giphy, Tenor, ou seu próprio servidor)', 'label': 'URL do GIF'}), 9: ('wagtail.blocks.StructBlock', [[('gif_url', 8), ('caption', 5)]], {}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'Cole a URL do arquivo de áudio (MP3, WAV, etc.)', 'label': 'URL do Áudio'}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Título do Áudio', 'required': False}), 12: ('wagtail.blocks.TextBlock', (), {'label': 'Descrição', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('audio_url', 10), ('title', 11), ('description', 12)]], {}), 14: ('wagtail.blocks.URLBlock', (), {'help_text': 'Cole a URL do arquivo PDF para download', 'label': 'URL do PDF'}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Baixar PDF', 'label': 'Título do Documento'}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Descrição opcional do documento', 'label': 'Descrição', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('pdf_url', 14), ('title', 15), ('description', 16)]], {}), 18: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Cole o link do vídeo do YouTube, Vimeo ou outra plataforma', 'label': 'Vídeo (YouTube, Vimeo, etc.)'}), 19: ('wagtail.blocks.TextBlock', (), {'label': 'Texto da Citação'}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Autor', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('text', 19), ('author', 20)]], {'icon': 'openquote', 'label': 'Citação'}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Item'}), 23: ('wagtail.blocks.ListBlock', (22,), {'help_text': 'Adicione uma lista de itens', 'label': 'Lista'}), 24: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Uma linha horizontal para separar seções', 'label': 'Divisor', 'template': 'content/blocks/divider.html'}), 25: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Adicione HTML personalizado (use com cuidado)', 'label': 'HTML Customizado'})}, null=True, verbose_name='Conteúdo do Artigo'),
        ),
    ]
