# Generated by Django 5.2.7 on 2025-10-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_videospage_alter_articlepage_content_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='subtitle_font',
            field=models.CharField(choices=[('Roboto', 'Roboto (Padrão)'), ('Playfair Display', 'Playfair Display (Elegante)'), ('Merriweather', 'Merriweather (Clássico)'), ('Montserrat', 'Montserrat (Moderno)'), ('Lora', 'Lora (Serifa)'), ('Open Sans', 'Open Sans (Clean)'), ('PT Serif', 'PT Serif (Jornal)'), ('Georgia', 'Georgia (Tradicional)')], default='Merriweather', help_text='Escolha a fonte para o subtítulo/introdução da seção', max_length=100, verbose_name='Fonte do Subtítulo'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='subtitle_size',
            field=models.CharField(choices=[('2rem', 'Pequeno (2rem)'), ('2.5rem', 'Médio (2.5rem)'), ('3rem', 'Grande (3rem)'), ('3.5rem', 'Extra Grande (3.5rem)'), ('4rem', 'Muito Grande (4rem)')], default='2rem', help_text='Escolha o tamanho do subtítulo/introdução da seção', max_length=20, verbose_name='Tamanho do Subtítulo'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='title_font',
            field=models.CharField(choices=[('Roboto', 'Roboto (Padrão)'), ('Playfair Display', 'Playfair Display (Elegante)'), ('Merriweather', 'Merriweather (Clássico)'), ('Montserrat', 'Montserrat (Moderno)'), ('Lora', 'Lora (Serifa)'), ('Open Sans', 'Open Sans (Clean)'), ('PT Serif', 'PT Serif (Jornal)'), ('Georgia', 'Georgia (Tradicional)')], default='Roboto', help_text='Escolha a fonte para o título da seção', max_length=100, verbose_name='Fonte do Título'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='title_size',
            field=models.CharField(choices=[('2rem', 'Pequeno (2rem)'), ('2.5rem', 'Médio (2.5rem)'), ('3rem', 'Grande (3rem)'), ('3.5rem', 'Extra Grande (3.5rem)'), ('4rem', 'Muito Grande (4rem)')], default='3rem', help_text='Escolha o tamanho do título da seção', max_length=20, verbose_name='Tamanho do Título'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='section',
            field=models.CharField(choices=[('em-alta', 'Em Alta'), ('geopolitica', 'Geopolítica'), ('economia', 'Economia'), ('clima', 'Clima'), ('tecnologia', 'Tecnologia')], default='em-alta', help_text='Escolha a seção deste artigo', max_length=50, verbose_name='Seção'),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='section_key',
            field=models.CharField(choices=[('em-alta', 'Em Alta'), ('geopolitica', 'Geopolítica'), ('economia', 'Economia'), ('clima', 'Clima'), ('tecnologia', 'Tecnologia')], help_text='Chave da seção que esta página representa', max_length=50, unique=True, verbose_name='Seção'),
        ),
    ]
