# Generated by Django 5.2.7 on 2025-10-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_add_section_customization'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, help_text='Texto introdutório para esta seção de apoio', verbose_name='Introdução da Seção de Apoio')),
                ('title_font', models.CharField(choices=[('Roboto', 'Roboto (Padrão)'), ('Playfair Display', 'Playfair Display (Elegante)'), ('Merriweather', 'Merriweather (Clássico)'), ('Montserrat', 'Montserrat (Moderno)'), ('Lora', 'Lora (Serifa)'), ('Open Sans', 'Open Sans (Clean)'), ('PT Serif', 'PT Serif (Jornal)'), ('Georgia', 'Georgia (Tradicional)')], default='Roboto', help_text='Escolha a fonte para o título da seção', max_length=100, verbose_name='Fonte do Título')),
                ('title_size', models.CharField(choices=[('2rem', 'Pequeno (2rem)'), ('2.5rem', 'Médio (2.5rem)'), ('3rem', 'Grande (3rem)'), ('3.5rem', 'Extra Grande (3.5rem)'), ('4rem', 'Muito Grande (4rem)')], default='3rem', help_text='Escolha o tamanho do título da seção', max_length=20, verbose_name='Tamanho do Título')),
                ('subtitle_font', models.CharField(choices=[('Roboto', 'Roboto (Padrão)'), ('Playfair Display', 'Playfair Display (Elegante)'), ('Merriweather', 'Merriweather (Clássico)'), ('Montserrat', 'Montserrat (Moderno)'), ('Lora', 'Lora (Serifa)'), ('Open Sans', 'Open Sans (Clean)'), ('PT Serif', 'PT Serif (Jornal)'), ('Georgia', 'Georgia (Tradicional)')], default='Merriweather', help_text='Escolha a fonte para o subtítulo/introdução da seção', max_length=100, verbose_name='Fonte do Subtítulo')),
                ('subtitle_size', models.CharField(choices=[('2rem', 'Pequeno (2rem)'), ('2.5rem', 'Médio (2.5rem)'), ('3rem', 'Grande (3rem)'), ('3.5rem', 'Extra Grande (3.5rem)'), ('4rem', 'Muito Grande (4rem)')], default='2rem', help_text='Escolha o tamanho do subtítulo/introdução da seção', max_length=20, verbose_name='Tamanho do Subtítulo')),
            ],
            options={
                'verbose_name': 'Seção de Apoio',
                'verbose_name_plural': 'Seções de Apoio',
            },
            bases=('wagtailcore.page',),
        ),
    ]
