# Generated by Django 5.2.7 on 2025-10-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_add_support_section_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='subtitle_size',
            field=models.CharField(choices=[('1rem', 'Muito Pequeno (1rem)'), ('1.5rem', 'Pequeno (1.5rem)'), ('2rem', 'Médio (2rem)'), ('2.5rem', 'Grande (2.5rem)'), ('3rem', 'Muito Grande (3rem)'), ('3.5rem', 'Extra Grande (3.5rem)'), ('4rem', 'Enorme (4rem)')], default='2rem', help_text='Escolha o tamanho do subtítulo/introdução da seção', max_length=20, verbose_name='Tamanho do Subtítulo'),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='title_size',
            field=models.CharField(choices=[('1rem', 'Muito Pequeno (1rem)'), ('1.5rem', 'Pequeno (1.5rem)'), ('2rem', 'Médio (2rem)'), ('2.5rem', 'Grande (2.5rem)'), ('3rem', 'Muito Grande (3rem)'), ('3.5rem', 'Extra Grande (3.5rem)'), ('4rem', 'Enorme (4rem)')], default='3rem', help_text='Escolha o tamanho do título da seção', max_length=20, verbose_name='Tamanho do Título'),
        ),
        migrations.AlterField(
            model_name='supportsectionpage',
            name='subtitle_size',
            field=models.CharField(choices=[('1rem', 'Muito Pequeno (1rem)'), ('1.5rem', 'Pequeno (1.5rem)'), ('2rem', 'Médio (2rem)'), ('2.5rem', 'Grande (2.5rem)'), ('3rem', 'Muito Grande (3rem)'), ('3.5rem', 'Extra Grande (3.5rem)'), ('4rem', 'Enorme (4rem)')], default='2rem', help_text='Escolha o tamanho do subtítulo/introdução da seção', max_length=20, verbose_name='Tamanho do Subtítulo'),
        ),
        migrations.AlterField(
            model_name='supportsectionpage',
            name='title_size',
            field=models.CharField(choices=[('1rem', 'Muito Pequeno (1rem)'), ('1.5rem', 'Pequeno (1.5rem)'), ('2rem', 'Médio (2rem)'), ('2.5rem', 'Grande (2.5rem)'), ('3rem', 'Muito Grande (3rem)'), ('3.5rem', 'Extra Grande (3.5rem)'), ('4rem', 'Enorme (4rem)')], default='3rem', help_text='Escolha o tamanho do título da seção', max_length=20, verbose_name='Tamanho do Título'),
        ),
    ]
