# Generated by Django 5.2.7 on 2025-10-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_update_size_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_tagline',
            field=models.CharField(default='Reconstruindo o sentido no fim da era antiga.', help_text='Texto que aparece no rodapé do site', max_length=200, verbose_name='Frase do Rodapé'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_tagline_size',
            field=models.CharField(choices=[('0.6rem', 'Muito Pequeno'), ('0.7rem', 'Pequeno (Padrão)'), ('0.8rem', 'Médio'), ('0.9rem', 'Grande'), ('1rem', 'Muito Grande'), ('1.1rem', 'Extra Grande')], default='0.7rem', help_text='Escolha o tamanho da frase que aparece no rodapé', max_length=20, verbose_name='Tamanho da Frase do Rodapé'),
        ),
    ]
