# Generated by Django 5.2.7 on 2025-10-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_add_footer_tagline_to_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='featured_image_caption',
            field=models.CharField(blank=True, help_text='Legenda descritiva para a imagem de destaque', max_length=255, verbose_name='Legenda da Imagem de Destaque'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='featured_image_caption_position',
            field=models.CharField(choices=[('text-start', 'Início (Esquerda)'), ('text-center', 'Centro'), ('text-end', 'Fim (Direita)')], default='text-start', help_text='Escolha onde a legenda e créditos devem aparecer', max_length=20, verbose_name='Posição da Legenda'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='featured_image_credit',
            field=models.CharField(blank=True, help_text='Créditos/fonte da imagem (ex: Foto de João Silva/Reuters)', max_length=255, verbose_name='Créditos da Imagem de Destaque'),
        ),
    ]
