# Generated by Django 5.2.7 on 2025-10-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_articlepage_content_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='is_trending',
            field=models.BooleanField(default=False, help_text="Artigos marcados como 'Em Alta' aparecem com destaque e emoji de fogo. Novos artigos são automaticamente marcados por 3 horas.", verbose_name='Em Alta?'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='trending_until',
            field=models.DateTimeField(blank=True, help_text='Data/hora até quando o artigo permanecerá em alta (automático para novos artigos)', null=True, verbose_name='Em Alta Até'),
        ),
    ]
