# Generated by Django 5.2.7 on 2025-10-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_articlepage_is_trending_articlepage_trending_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='columns_desktop',
            field=models.IntegerField(choices=[(1, '1 Coluna'), (2, '2 Colunas'), (3, '3 Colunas'), (4, '4 Colunas')], default=3, help_text='Número de colunas no desktop (>= 1024px)', verbose_name='Colunas (Desktop)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='columns_mobile',
            field=models.IntegerField(choices=[(1, '1 Coluna'), (2, '2 Colunas')], default=1, help_text='Número de colunas no mobile (< 768px)', verbose_name='Colunas (Mobile)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='grid_gap',
            field=models.CharField(choices=[('0.5rem', 'Pequeno (0.5rem)'), ('1rem', 'Médio (1rem)'), ('1.5rem', 'Grande (1.5rem)'), ('2rem', 'Extra Grande (2rem)')], default='1rem', help_text='Espaço entre os cards de artigos', max_length=20, verbose_name='Espaçamento entre Cards'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_layout_preset',
            field=models.CharField(choices=[('three_column_grid', 'Grade de 3 Colunas (Padrão)'), ('two_column_grid', 'Grade de 2 Colunas'), ('list_with_dividers', 'Lista com Divisores'), ('feature_top_grid', 'Destaque no Topo + Grade'), ('masonry_light', 'Masonry Leve (Pinterest-style)')], default='three_column_grid', help_text='Escolha o estilo de layout para a página inicial', max_length=50, verbose_name='Preset de Layout da Home'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_dividers',
            field=models.BooleanField(default=False, help_text='Adiciona linhas divisórias entre artigos (melhor para layout de lista)', verbose_name='Mostrar Divisores?'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_trending_section',
            field=models.BooleanField(default=True, help_text='Exibe ou oculta a seção de artigos em alta', verbose_name="Mostrar Seção 'Em Alta'?"),
        ),
    ]
