# Generated by Django 5.2.7 on 2025-10-18 05:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_add_homepage_layout_configuration"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="curated_sections",
            field=wagtail.fields.StreamField(
                [("curated_section", 8)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Título da Seção"}),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Linha de Apoio", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("grid", "Grade Equilibrada"),
                                ("list", "Lista Editorial"),
                                ("split", "Destaque + Lista"),
                            ],
                            "label": "Estilo da Listagem",
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("economist-red", "Vermelho The Economist"),
                                ("ink", "Azul Escuro"),
                                ("charcoal", "Cinza Carvão"),
                                ("sand", "Areia Quente"),
                            ],
                            "label": "Cor de Destaque",
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Texto do Link/CTA", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Opcional – deixa a seção com um link para ver todos os artigos da editoria",
                            "label": "URL do CTA",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["content.ArticlePage"]},
                    ),
                    7: (
                        "wagtail.blocks.ListBlock",
                        (6,),
                        {
                            "help_text": "Escolha manualmente quais artigos aparecem nesta seção",
                            "label": "Artigos Selecionados",
                            "min_num": 1,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("layout_style", 2),
                                ("accent", 3),
                                ("call_to_action_text", 4),
                                ("call_to_action_url", 5),
                                ("articles", 7),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Seções Editoriais Curadas",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="divider_style",
            field=models.CharField(
                choices=[
                    ("thin", "Linha Fina Clássica"),
                    ("thick", "Linha Grossa Editorial"),
                    ("double", "Linha Dupla"),
                ],
                default="thin",
                help_text="Define como as linhas divisórias aparecem entre as seções",
                max_length=20,
                verbose_name="Estilo dos Divisores",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Imagem aplicada como textura sutil atrás do destaque",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagem de Fundo do Destaque",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_button_text",
            field=models.CharField(
                blank=True,
                help_text="Etiqueta do botão exibido no destaque principal",
                max_length=60,
                verbose_name="Texto do Botão",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_button_url",
            field=models.URLField(
                blank=True,
                help_text="Link opcional para guiar o leitor (ex: assinatura, newsletter)",
                verbose_name="URL do Botão",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_kicker",
            field=models.CharField(
                blank=True,
                help_text="Linha superior curta, ex: 'Análise Especial'",
                max_length=120,
                verbose_name="Kicker do Destaque",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle",
            field=models.TextField(
                blank=True,
                help_text="Texto que aparece ao lado do artigo em destaque",
                verbose_name="Resumo Editorial",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="show_videos_section",
            field=models.BooleanField(
                default=True, verbose_name="Mostrar seção de vídeos?"
            ),
        ),
    ]
