# Generated by Django 5.2.7 on 2025-10-18 06:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0022_homepage_curated_sections_homepage_divider_style_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="highlight_video_mime_type",
            field=models.CharField(
                choices=[
                    ("video/mp4", "MP4 (video/mp4)"),
                    ("video/webm", "WebM (video/webm)"),
                    ("video/ogg", "Ogg/Theora (video/ogg)"),
                ],
                default="video/mp4",
                help_text="Seleciona o mime type usado ao renderizar o vídeo de destaque.",
                max_length=20,
                verbose_name="Formato do Vídeo de Destaque",
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="highlight_video_poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Thumbnail do Vídeo de Destaque",
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="highlight_video_poster_url",
            field=models.URLField(
                blank=True,
                help_text="URL opcional para imagem de capa do vídeo quando hospedada externamente.",
                verbose_name="Thumbnail Externo do Vídeo de Destaque",
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="highlight_video_url",
            field=models.URLField(
                blank=True,
                help_text="Link direto para um vídeo hospedado externamente (MP4, WebM, etc.) para uso no destaque da home.",
                verbose_name="URL do Vídeo de Destaque",
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="content_blocks",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("heading", 1),
                    ("image", 2),
                    ("image_url", 8),
                    ("gif", 10),
                    ("audio", 14),
                    ("custom_video", 22),
                    ("pdf_download", 26),
                    ("video", 27),
                    ("quote", 30),
                    ("list", 32),
                    ("divider", 33),
                    ("fonte_link", 36),
                    ("html", 37),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "code",
                                "superscript",
                                "subscript",
                                "blockquote",
                            ],
                            "help_text": "Adicione parágrafos de texto com formatação completa",
                            "label": "Parágrafo",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "help_text": "Adicione um título de seção",
                            "label": "Título/Subtítulo",
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Insira uma imagem do banco de dados",
                            "label": "Imagem (Somente Upload)",
                        },
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Imagem (Upload)", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Ou use uma URL de imagem externa",
                            "label": "URL da Imagem",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Legenda", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Crédito", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text-start", "Início (Esquerda)"),
                                ("text-center", "Centro"),
                                ("text-end", "Fim (Direita)"),
                            ],
                            "help_text": "Escolha onde a legenda e créditos devem aparecer",
                            "label": "Posição da Legenda",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 3),
                                ("image_url", 4),
                                ("caption", 5),
                                ("credit", 6),
                                ("caption_position", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Cole a URL do GIF (ex: de um serviço como Giphy, Tenor, ou seu próprio servidor)",
                            "label": "URL do GIF",
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("gif_url", 9),
                                ("caption", 5),
                                ("credit", 6),
                                ("caption_position", 7),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Cole a URL do arquivo de áudio (MP3, WAV, etc.)",
                            "label": "URL do Áudio",
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Título do Áudio", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Descrição", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("audio_url", 11), ("title", 12), ("description", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Cole o link direto do arquivo hospedado (MP4, WebM, etc.)",
                            "label": "URL do Vídeo",
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("video/mp4", "MP4 (video/mp4)"),
                                ("video/webm", "WebM (video/webm)"),
                                ("video/ogg", "Ogg/Theora (video/ogg)"),
                            ],
                            "help_text": "Selecione o formato/mime type correspondente ao arquivo",
                            "label": "Formato do Vídeo",
                        },
                    ),
                    17: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Imagem exibida antes da reprodução (opcional)",
                            "label": "Thumbnail do Vídeo (Upload)",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Opcionalmente use uma imagem hospedada externamente",
                            "label": "Thumbnail do Vídeo (URL externa)",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Texto curto exibido abaixo do player (opcional)",
                            "label": "Legenda",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("narrow", "Estreito (até 640px)"),
                                ("standard", "Padrão (até 860px)"),
                                ("wide", "Amplo (até 1040px)"),
                                ("full", "Largura Total"),
                            ],
                            "help_text": "Controle a largura máxima do player dentro do artigo",
                            "label": "Largura do Player",
                        },
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("16x9", "16:9 (Widescreen)"),
                                ("4x3", "4:3 (Clássico)"),
                                ("1x1", "1:1 (Quadrado)"),
                                ("21x9", "21:9 (Cinemascope)"),
                            ],
                            "help_text": "Escolha a proporção para manter o vídeo responsivo",
                            "label": "Proporção do Vídeo",
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video_url", 15),
                                ("mime_type", 16),
                                ("poster_image", 17),
                                ("poster_image_url", 18),
                                ("caption", 19),
                                ("width", 20),
                                ("aspect_ratio", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Cole a URL do arquivo PDF para download",
                            "label": "URL do PDF",
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Baixar PDF", "label": "Título do Documento"},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Descrição opcional do documento",
                            "label": "Descrição",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("pdf_url", 23), ("title", 24), ("description", 25)]],
                        {},
                    ),
                    27: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Cole o link do vídeo do YouTube, Vimeo ou outra plataforma",
                            "label": "Vídeo (YouTube, Vimeo, etc.)",
                        },
                    ),
                    28: ("wagtail.blocks.TextBlock", (), {"label": "Texto da Citação"}),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Autor", "required": False},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 28), ("author", 29)]],
                        {"icon": "openquote", "label": "Citação"},
                    ),
                    31: ("wagtail.blocks.CharBlock", (), {"label": "Item"}),
                    32: (
                        "wagtail.blocks.ListBlock",
                        (31,),
                        {"help_text": "Adicione uma lista de itens", "label": "Lista"},
                    ),
                    33: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Uma linha horizontal para separar seções",
                            "label": "Divisor",
                            "template": "content/blocks/divider.html",
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Texto que aparecerá clicável (ex: CNN, Reuters, BBC)",
                            "label": "Texto da Fonte",
                            "required": True,
                        },
                    ),
                    35: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link completo para a fonte (ex: https://www.cnnbrasil.com.br/...)",
                            "label": "URL da Fonte",
                            "required": True,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("texto", 34), ("link", 35)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "help_text": "Adicione HTML personalizado (use com cuidado)",
                            "label": "HTML Customizado",
                        },
                    ),
                },
                null=True,
                verbose_name="Conteúdo do Artigo",
            ),
        ),
    ]
