# Generated by Django 5.2.7 on 2025-10-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0023_articlepage_highlight_video_mime_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="video_section_position",
            field=models.CharField(
                choices=[
                    ("below_highlight", "Abaixo do destaque principal"),
                    ("below_recent", 'Abaixo de "Análises Recentes"'),
                ],
                default="below_highlight",
                help_text="Controle se a vitrine de vídeos fica abaixo do destaque principal ou das análises recentes.",
                max_length=30,
                verbose_name="Posição dos vídeos curtos",
            ),
        ),
        migrations.AddField(
            model_name="sitecustomization",
            name="announcement_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Mostra uma faixa acima do cabeçalho com mensagens editoriais ou campanhas.",
                verbose_name="Ativar barra de anúncio/editorial?",
            ),
        ),
        migrations.AddField(
            model_name="sitecustomization",
            name="announcement_link_text",
            field=models.CharField(
                blank=True,
                help_text="Opcional. Se preenchido, um botão será exibido ao lado da mensagem.",
                max_length=60,
                verbose_name="Texto do botão do anúncio",
            ),
        ),
        migrations.AddField(
            model_name="sitecustomization",
            name="announcement_link_url",
            field=models.URLField(
                blank=True,
                help_text="URL aberta ao clicar no botão da barra promocional.",
                verbose_name="Link do anúncio",
            ),
        ),
        migrations.AddField(
            model_name="sitecustomization",
            name="announcement_text",
            field=models.CharField(
                blank=True,
                help_text="Texto curto exibido na barra promocional do topo.",
                max_length=150,
                verbose_name="Mensagem do anúncio",
            ),
        ),
        migrations.AddField(
            model_name="sitecustomization",
            name="enable_dark_mode_toggle",
            field=models.BooleanField(
                default=False,
                help_text="Exibe um botão no menu para que os leitores alternem entre modo claro e escuro.",
                verbose_name="Mostrar alternância de modo escuro?",
            ),
        ),
        migrations.AddField(
            model_name="sitecustomization",
            name="short_videos_cta_label",
            field=models.CharField(
                blank=True,
                default="Ver todos",
                help_text="Etiqueta do link de ação ao lado do título. Deixe em branco para ocultar.",
                max_length=40,
                verbose_name="Texto do link da seção de vídeos",
            ),
        ),
        migrations.AddField(
            model_name="sitecustomization",
            name="short_videos_cta_url",
            field=models.URLField(
                blank=True,
                help_text="Para onde o visitante é levado ao clicar no CTA da seção de vídeos.",
                verbose_name="URL do link da seção de vídeos",
            ),
        ),
        migrations.AddField(
            model_name="sitecustomization",
            name="short_videos_description",
            field=models.CharField(
                blank=True,
                help_text="Linha auxiliar exibida abaixo do título (opcional).",
                max_length=160,
                verbose_name="Descrição da seção de vídeos",
            ),
        ),
        migrations.AddField(
            model_name="sitecustomization",
            name="short_videos_title",
            field=models.CharField(
                default="Vídeos em Destaque",
                help_text="Texto exibido no topo da vitrine de vídeos curtos.",
                max_length=80,
                verbose_name="Título da seção de vídeos",
            ),
        ),
        migrations.AddField(
            model_name="sitecustomization",
            name="show_scroll_progress",
            field=models.BooleanField(
                default=True,
                help_text="Controla a barra fina no topo que indica o quanto do artigo já foi lido.",
                verbose_name="Exibir barra de progresso de leitura?",
            ),
        ),
        migrations.AddField(
            model_name="sitecustomization",
            name="whatsapp_contact_url",
            field=models.URLField(
                blank=True,
                help_text="Exibe um botão flutuante para contato rápido via WhatsApp, Telegram ou similar.",
                verbose_name="Link de contato (WhatsApp/Telegram)",
            ),
        ),
        migrations.AddField(
            model_name="videoshort",
            name="cdn_mime_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("video/mp4", "MP4 (video/mp4)"),
                    ("video/webm", "WebM (video/webm)"),
                    ("video/ogg", "Ogg/Theora (video/ogg)"),
                ],
                help_text="Obrigatório para arquivos diretos. Ajuda os navegadores a detectar o formato corretamente.",
                max_length=20,
                verbose_name="Formato do Vídeo (CDN)",
            ),
        ),
        migrations.AddField(
            model_name="videoshort",
            name="cdn_video_url",
            field=models.URLField(
                blank=True,
                help_text="Forneça o link direto (MP4, WebM, etc.) quando utilizar um arquivo próprio em CDN.",
                verbose_name="URL do Vídeo (CDN)",
            ),
        ),
        migrations.AddField(
            model_name="videoshort",
            name="video_source_type",
            field=models.CharField(
                choices=[
                    ("platform", "Plataforma (YouTube, Vimeo, etc.)"),
                    ("cdn", "Arquivo direto em CDN"),
                ],
                default="platform",
                help_text="Escolha entre incorporar de uma plataforma ou carregar o player com um arquivo em CDN.",
                max_length=20,
                verbose_name="Origem do Vídeo",
            ),
        ),
        migrations.AlterField(
            model_name="videoshort",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL do vídeo (YouTube, Vimeo, etc.)",
                verbose_name="URL do Vídeo",
            ),
        ),
    ]
